name: Makefile CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest
    container: pgxn/pgxn-tools

    steps:
      - run: pg-start 15
      - uses: actions/checkout@v4
      - run: pg-build-test
